services:
  crm-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-frontend
    ports:
      - "3028:3028"
    env_file:
      - .env.production
    volumes:
      - ./config:/app/config
      - ./messages:/app/messages
    restart: unless-stopped
